const requireElement = <T extends Element>(selector: string) => {
  const element = document.querySelector<T>(selector);
  if (!element) throw new Error(`Missing renderer element: ${selector}`);
  return element;
};

export const getRendererElements = () => ({
  onboarding: requireElement<HTMLDivElement>("#onboarding"),
  appView: requireElement<HTMLDivElement>("#appView"),
  onboardingStatus: requireElement<HTMLParagraphElement>("#onboardingStatus"),
  appGrid: requireElement<HTMLDivElement>("#appGrid"),
  onboardingCapabilities: requireElement<HTMLDivElement>("#onboardingCapabilities"),
  runtimeCapabilities: requireElement<HTMLDivElement>("#runtimeCapabilities"),
  authorizedApps: requireElement<HTMLDivElement>("#authorizedApps"),
  statusText: requireElement<HTMLParagraphElement>("#statusText"),
  contextApp: requireElement<HTMLElement>("#contextApp"),
  contextWindow: requireElement<HTMLElement>("#contextWindow"),
  contextClipboard: requireElement<HTMLElement>("#contextClipboard"),
  contextRecentFiles: requireElement<HTMLElement>("#contextRecentFiles"),
  connectBtn: requireElement<HTMLButtonElement>("#connectBtn"),
  disconnectBtn: requireElement<HTMLButtonElement>("#disconnectBtn"),
  orbOnlyBtn: requireElement<HTMLButtonElement>("#orbOnlyBtn"),
  restorePanelBtn: requireElement<HTMLButtonElement>("#restorePanelBtn"),
  sendTextBtn: requireElement<HTMLButtonElement>("#sendTextBtn"),
  textInput: requireElement<HTMLInputElement>("#textInput"),
  transcript: requireElement<HTMLDivElement>("#transcript"),
  miniPlayer: requireElement<HTMLDivElement>("#miniPlayer"),
  miniPlayerArtwork: requireElement<HTMLImageElement>("#miniPlayerArtwork"),
  miniPlayerTitle: requireElement<HTMLElement>("#miniPlayerTitle"),
  miniPlayerArtist: requireElement<HTMLSpanElement>("#miniPlayerArtist"),
  miniPlayerPlayBtn: requireElement<HTMLButtonElement>("#miniPlayerPlayBtn"),
  miniPlayerPauseBtn: requireElement<HTMLButtonElement>("#miniPlayerPauseBtn"),
  confirmations: requireElement<HTMLDivElement>("#confirmations"),
  activity: requireElement<HTMLDivElement>("#activity"),
  resultWindow: requireElement<HTMLDivElement>("#resultWindow"),
  resultWindowTitle: requireElement<HTMLHeadingElement>("#resultWindowTitle"),
  resultWindowSubtitle: requireElement<HTMLParagraphElement>("#resultWindowSubtitle"),
  resultWindowBody: requireElement<HTMLDivElement>("#resultWindowBody"),
  resultWindowCloseBtn: requireElement<HTMLButtonElement>("#resultWindowCloseBtn"),
  orbMount: requireElement<HTMLDivElement>("#orbMount"),
  glassReply: requireElement<HTMLDivElement>("#glassReply"),
  glassReplyText: requireElement<HTMLSpanElement>("#glassReplyText"),
  userMeter: requireElement<HTMLSpanElement>("#userMeter"),
  aiMeter: requireElement<HTMLSpanElement>("#aiMeter"),
  finishOnboardingBtn: requireElement<HTMLButtonElement>("#finishOnboardingBtn"),
  onboardingYoloBtn: requireElement<HTMLButtonElement>("#onboardingYoloBtn"),
  refreshAppsBtn: requireElement<HTMLButtonElement>("#refreshAppsBtn"),
  openPermissionsBtn: requireElement<HTMLButtonElement>("#openPermissionsBtn"),
  manageAppsBtn: requireElement<HTMLButtonElement>("#manageAppsBtn"),
  yoloModeBtn: requireElement<HTMLButtonElement>("#yoloModeBtn"),
  yoloModeStatus: requireElement<HTMLParagraphElement>("#yoloModeStatus"),
  openaiKeyInput: requireElement<HTMLInputElement>("#openaiKeyInput"),
  saveOpenaiKeyBtn: requireElement<HTMLButtonElement>("#saveOpenaiKeyBtn"),
  openaiKeyStatus: requireElement<HTMLParagraphElement>("#openaiKeyStatus"),
  openaiKeyBadge: requireElement<HTMLSpanElement>("#openaiKeyBadge"),
  betaSetupBadge: requireElement<HTMLSpanElement>("#betaSetupBadge"),
  betaSetupList: requireElement<HTMLDivElement>("#betaSetupList"),
  betaFeedbackInput: requireElement<HTMLTextAreaElement>("#betaFeedbackInput"),
  exportDiagnosticsBtn: requireElement<HTMLButtonElement>("#exportDiagnosticsBtn"),
  exportFeedbackBtn: requireElement<HTMLButtonElement>("#exportFeedbackBtn"),
  diagnosticsStatus: requireElement<HTMLParagraphElement>("#diagnosticsStatus"),
  realtimeVoiceSelect: requireElement<HTMLSelectElement>("#realtimeVoiceSelect"),
  realtimeVoiceStatus: requireElement<HTMLParagraphElement>("#realtimeVoiceStatus"),
  realtimeVoiceBadge: requireElement<HTMLSpanElement>("#realtimeVoiceBadge"),
  musicKitBadge: requireElement<HTMLSpanElement>("#musicKitBadge"),
  musicKitStatus: requireElement<HTMLParagraphElement>("#musicKitStatus"),
  authorizeMusicKitBtn: requireElement<HTMLButtonElement>("#authorizeMusicKitBtn"),
  codexLoginBadge: requireElement<HTMLSpanElement>("#codexLoginBadge"),
  codexLoginStatus: requireElement<HTMLParagraphElement>("#codexLoginStatus"),
  refreshCodexLoginBtn: requireElement<HTMLButtonElement>("#refreshCodexLoginBtn"),
  startCodexLoginBtn: requireElement<HTMLButtonElement>("#startCodexLoginBtn"),
  codexLoginOutput: requireElement<HTMLPreElement>("#codexLoginOutput"),
  codexModelSelect: requireElement<HTMLSelectElement>("#codexModelSelect"),
  codexModelStatus: requireElement<HTMLParagraphElement>("#codexModelStatus"),
  refreshTasksBtn: requireElement<HTMLButtonElement>("#refreshTasksBtn"),
  taskRuns: requireElement<HTMLDivElement>("#taskRuns"),
  refreshWorkflowsBtn: requireElement<HTMLButtonElement>("#refreshWorkflowsBtn"),
  workflowPacks: requireElement<HTMLDivElement>("#workflowPacks"),
  refreshArtifactsBtn: requireElement<HTMLButtonElement>("#refreshArtifactsBtn"),
  artifactList: requireElement<HTMLDivElement>("#artifactList"),
  refreshAgentRunsBtn: requireElement<HTMLButtonElement>("#refreshAgentRunsBtn"),
  agentRuns: requireElement<HTMLDivElement>("#agentRuns"),
  microphoneSelect: requireElement<HTMLSelectElement>("#microphoneSelect"),
  refreshMicrophonesBtn: requireElement<HTMLButtonElement>("#refreshMicrophonesBtn"),
  microphoneStatus: requireElement<HTMLParagraphElement>("#microphoneStatus"),
  realtimeUsage: requireElement<HTMLDivElement>("#realtimeUsage"),
});

export type RendererElements = ReturnType<typeof getRendererElements>;
