import type { ToolName } from "../../shared/tools";
import type { ToolHandler } from "./define-tool";

export type ToolHandlerRuntime = {
  invokeToolHandler: (name: ToolName, args: Record<string, unknown>, source: "realtime" | "local") => Promise<unknown> | unknown;
};

export const toolHandlerNames = [
  "system_status",
  "confirmation_list",
  "confirmation_decide",
  "tool_result_read",
  "tool_catalog_list",
  "tool_group_set",
  "task_create",
  "task_status",
  "task_list",
  "task_cancel",
  "task_route",
  "intent_route",
  "memory_lookup",
  "memory_save",
  "memory_forget",
  "memory_status",
  "codex_task_run",
  "yolo_mode_set",
  "app_permission_search",
  "app_permission_set",
  "capability_set",
  "file_list",
  "file_search",
  "file_read",
  "file_open",
  "file_create_folder",
  "file_rename",
  "file_move",
  "file_copy",
  "file_trash",
  "document_extract",
  "document_folder_digest",
  "document_prepare_edit",
  "email_search",
  "email_read",
  "email_draft",
  "email_send",
  "mac_mail_draft_create",
  "calendar_search",
  "weather_lookup",
  "calendar_create",
  "mac_calendar_create",
  "mac_reminder_create",
  "mac_note_create",
  "copy_search",
  "copy_save_draft",
  "copy_publish",
  "music_open",
  "music_play_song",
  "music_playback_state",
  "music_spotify_search",
  "music_spotify_play",
  "music_spotify_playback_state",
  "music_netease_open",
  "music_qq_open",
  "media_key_control",
  "video_play",
  "video_playback_control",
  "apple_tv_playback_state",
  "social_x_search",
  "social_x_post",
  "social_open",
  "news_search",
  "sec_filing_search",
  "macro_series_lookup",
  "market_quote_lookup",
  "shortcut_list",
  "shortcut_run",
  "contacts_search",
  "phone_call",
  "app_open",
  "app_focus",
  "app_quit",
  "window_list",
  "window_close_all",
  "window_hide_all",
  "window_minimize_all",
  "window_auto_arrange",
  "window_minimize_unrelated",
  "window_close",
  "window_minimize",
  "window_maximize",
  "window_move_resize",
  "desktop_show",
  "desktop_open_app",
  "system_close_app",
  "system_sleep",
  "system_lock_screen",
  "system_set_volume",
  "system_get_volume",
  "system_mute_volume",
  "system_set_brightness",
  "system_set_dark_mode",
  "system_open_settings",
  "desktop_clipboard_write",
  "desktop_clipboard_read",
  "system_speak",
  "system_notification",
  "screenshot_capture",
  "keyboard_shortcut",
  "browser_open_url",
  "browser_search_open",
  "browser_isolated_open_url",
  "browser_isolated_window_focus",
  "browser_isolated_window_move_resize",
  "browser_read_page",
  "browser_read_video_state",
  "browser_fill_form",
  "browser_click",
  "advanced_shell_command",
] as const satisfies readonly ToolName[];

export const createToolHandlers = (runtime: ToolHandlerRuntime): Record<ToolName, ToolHandler<Record<string, unknown>>> =>
  Object.fromEntries(
    toolHandlerNames.map((name) => [
      name,
      (args: Record<string, unknown>, context) => runtime.invokeToolHandler(name, args, context.source),
    ]),
  ) as Record<ToolName, ToolHandler<Record<string, unknown>>>;

