import { z } from "zod";
import { config } from "../config";
type JsonSchema = Record<string, unknown>;

export type ToolGroup =
  | "permissions"
  | "files"
  | "documents"
  | "text"
  | "media"
  | "social"
  | "research"
  | "phone"
  | "apps"
  | "windows"
  | "system"
  | "browser"
  | "shell"
  | "agents";

export type ToolRisk =
  | "read"
  | "local_open"
  | "local_write"
  | "external_send"
  | "browser_submit"
  | "system_change"
  | "shell"
  | "coding_agent";

export const toolGroups = [
  "permissions",
  "files",
  "documents",
  "text",
  "media",
  "social",
  "research",
  "phone",
  "apps",
  "windows",
  "system",
  "browser",
  "shell",
  "agents",
] as const satisfies readonly ToolGroup[];

const objectSchema = (
  properties: Record<string, JsonSchema>,
  required: string[] = [],
): JsonSchema => ({
  type: "object",
  properties,
  required,
  additionalProperties: false,
});

export const allToolDefinitions = [
  {
    type: "function",
    name: "system_status",
    description: "Check local assistant capabilities, connected adapters, and current safety mode.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "confirmation_list",
    description: "List pending local confirmation requests that are waiting for the user's explicit approval or rejection.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "confirmation_decide",
    description: "Approve or reject a pending local confirmation after the user's latest voice/text message explicitly says to confirm, approve, reject, or cancel it. If only one confirmation is pending, confirmationId may be omitted.",
    parameters: objectSchema(
      {
        confirmationId: { type: "string", description: "Pending confirmation id. Optional only when exactly one confirmation is pending." },
        approved: { type: "boolean", description: "true to approve/confirm, false to reject/cancel." },
      },
      ["approved"],
    ),
  },
  {
    type: "function",
    name: "tool_result_read",
    description: "Read a bounded slice of a previous large tool result by handle. Use only after a tool result says it was truncated and provides a handle.",
    parameters: objectSchema(
      {
        handle: { type: "string", description: "Handle returned by a truncated tool result." },
        offset: { type: "integer", minimum: 0, default: 0 },
        maxChars: { type: "integer", minimum: 200, maximum: 6000, default: 2000 },
      },
      ["handle"],
    ),
  },
  {
    type: "function",
    name: "tool_catalog_list",
    description: "List available dynamic tool groups, or list the bounded tool catalog for one group. Call without group first; call again with a group only when you need tool names in that group.",
    parameters: objectSchema({
      group: { type: "string", enum: toolGroups, description: "Optional dynamic tool group to inspect." },
    }),
  },
  {
    type: "function",
    name: "tool_group_set",
    description: "Enable or disable a dynamic tool group for future queued tasks. Disabling a group prevents task_create from enqueueing tools in that group.",
    parameters: objectSchema(
      {
        group: { type: "string", enum: toolGroups },
        enabled: { type: "boolean" },
      },
      ["group", "enabled"],
    ),
  },
  {
    type: "function",
    name: "her_select_bundle",
    description: "Select the best HER dynamic Realtime tool bundles for the user's transcript when deterministic routing is uncertain.",
    parameters: objectSchema(
      {
        transcript: { type: "string", description: "The user's latest transcribed request." },
      },
      ["transcript"],
    ),
  },
  {
    type: "function",
    name: "task_create",
    description: "Create a local task queue item for any non-core tool. Realtime should use this instead of directly carrying large or side-effecting tool calls in session context.",
    parameters: objectSchema(
      {
        toolName: { type: "string", description: "Name from tool_catalog_list for the selected group." },
        arguments: { type: "object", description: "Arguments for the selected tool.", additionalProperties: true },
        priority: { type: "string", enum: ["low", "normal", "high"], default: "normal" },
        runAfterMs: { type: "integer", minimum: 0, maximum: 600000, default: 0 },
      },
      ["toolName", "arguments"],
    ),
  },
  {
    type: "function",
    name: "task_status",
    description: "Read one task by id, including status, confirmation id when waiting for approval, and compact result when complete.",
    parameters: objectSchema({ taskId: { type: "string" } }, ["taskId"]),
  },
  {
    type: "function",
    name: "task_list",
    description: "List recent task queue items with compact status. Use this to monitor queued or running work without loading large outputs.",
    parameters: objectSchema({
      status: { type: "string", enum: ["queued", "running", "awaiting_confirmation", "blocked", "completed", "failed", "cancelled", "needs_confirmation"] },
      limit: { type: "integer", minimum: 1, maximum: 30, default: 10 },
    }),
  },
  {
    type: "function",
    name: "task_cancel",
    description: "Cancel a queued task. Running tasks cannot be force-killed, but queued work is skipped.",
    parameters: objectSchema({ taskId: { type: "string" } }, ["taskId"]),
  },
  {
    type: "function",
    name: "task_events",
    description: "Read recent HER Task Runtime events for one task.",
    parameters: objectSchema(
      {
        taskId: { type: "string" },
        limit: { type: "integer", minimum: 1, maximum: 100, default: 50 },
      },
      ["taskId"],
    ),
  },
  {
    type: "function",
    name: "task_route",
    description: "Classify a user request into HER native tools, HER web search, Codex background runtime, or a mixed plan. Use before task_create when the best provider is unclear.",
    parameters: objectSchema(
      {
        userRequest: { type: "string", description: "The user's full request to route." },
        preference: { type: "string", enum: ["auto", "native", "search", "codex"], default: "auto" },
        cwd: { type: "string", description: "Optional working directory for Codex tasks." },
        activeApp: { type: "string", description: "Optional current/frontmost app name." },
        selectedText: { type: "string", description: "Optional selected text or short local context." },
      },
      ["userRequest"],
    ),
  },
  {
    type: "function",
    name: "intent_route",
    description: "Route a StandardIntent JSON object produced by Realtime. Realtime should parse natural language into this intent first; HER then chooses direct local tools or Codex.",
    parameters: objectSchema(
      {
        intent: {
          type: "object",
          description: "StandardIntent JSON with originalText, intent, complexity, domain, action, entities, toolName/toolArguments, missingInfo, and confidence.",
          properties: {
            originalText: { type: "string" },
            intent: { type: "string" },
            complexity: { type: "string", enum: ["simple", "complex", "ambiguous"] },
            domain: {
              type: "string",
              enum: [
                "desktop",
                "apps",
                "windows",
                "system",
                "media",
                "social",
                "calendar",
                "reminder",
                "notes",
                "weather",
                "travel",
                "browser",
                "files",
                "documents",
                "email",
                "coding",
                "research",
                "phone",
                "memory",
                "unknown",
              ],
            },
            action: { type: "string" },
            entities: { type: "object", additionalProperties: true },
            toolName: { type: "string", description: "Preferred HER tool for simple direct execution, when known." },
            toolArguments: { type: "object", additionalProperties: true },
            candidateTools: { type: "array", items: { type: "string" } },
            missingInfo: { type: "array", items: { type: "string" } },
            confidence: { type: "number", minimum: 0, maximum: 1 },
            routePreference: { type: "string", enum: ["auto", "direct", "codex", "clarify"] },
          },
          required: ["originalText", "intent", "complexity", "domain", "confidence"],
          additionalProperties: false,
        },
        cwd: { type: "string", description: "Optional working directory for Codex tasks." },
        activeApp: { type: "string", description: "Optional current/frontmost app name." },
        selectedText: { type: "string", description: "Optional selected text or short local context." },
      },
      ["intent"],
    ),
  },
  {
    type: "function",
    name: "memory_lookup",
    description: "Look up compact HER memory summaries such as path aliases, preferences, and task templates. Results are short; providers resolve full content internally when needed.",
    parameters: objectSchema(
      {
        query: { type: "string" },
        types: { type: "array", items: { type: "string", enum: ["path_alias", "preference", "task_template"] } },
        limit: { type: "integer", minimum: 1, maximum: 10, default: 5 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "memory_save",
    description: "Save a user-approved HER memory item. Use only when the user explicitly asks HER to remember a path, preference, or task template.",
    parameters: objectSchema(
      {
        type: { type: "string", enum: ["path_alias", "preference", "task_template"] },
        key: { type: "string" },
        value: { type: "string" },
        summary: { type: "string" },
        content: { type: "string" },
        aliases: { type: "array", items: { type: "string" } },
        tags: { type: "array", items: { type: "string" } },
      },
      ["type", "key"],
    ),
  },
  {
    type: "function",
    name: "memory_forget",
    description: "Forget a HER memory item by id or exact key. Use only when the user explicitly asks to forget it.",
    parameters: objectSchema({ idOrKey: { type: "string" } }, ["idOrKey"]),
  },
  {
    type: "function",
    name: "memory_status",
    description: "Return HER memory counts and storage status without exposing full memory content.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "alias_create",
    description: "Create or overwrite a user-approved personal alias that maps an exact phrase to one validated HER tool call. This stores persistent local memory and requires confirmation.",
    parameters: objectSchema(
      {
        phrase: { type: "string", description: "Exact phrase the user wants HER to remember, such as 打开 VPN." },
        toolName: { type: "string", description: "Existing HER target tool name from the manifest." },
        arguments: { type: "object", description: "Arguments for the target tool. Must validate against the target tool schema.", additionalProperties: true },
        description: { type: "string", description: "Optional short human-readable alias description." },
        overwrite: { type: "boolean", description: "Set true to replace an existing alias with the same normalized phrase.", default: false },
      },
      ["phrase", "toolName", "arguments"],
    ),
  },
  {
    type: "function",
    name: "alias_list",
    description: "List stored personal aliases. This is read-only and does not execute alias targets.",
    parameters: objectSchema({
      query: { type: "string", description: "Optional phrase filter." },
    }),
  },
  {
    type: "function",
    name: "alias_delete",
    description: "Delete a stored personal alias by id or phrase. This changes persistent memory and requires confirmation.",
    parameters: objectSchema({
      aliasId: { type: "string", description: "Alias id to delete." },
      phrase: { type: "string", description: "Alias phrase to delete when aliasId is not known." },
    }),
  },
  {
    type: "function",
    name: "codex_task_run",
    description: "Run a complex background intent through HER's Codex app-server runtime. Codex may request HER local tools only through HER Tool Gateway; HER validates and queues any requested side effects.",
    parameters: objectSchema(
      {
        prompt: { type: "string", description: "The complete task for HER's background Codex runtime." },
        cwd: { type: "string", description: "Optional working directory. Defaults to HER's current project directory." },
        model: { type: "string", description: "Optional Codex model override. Leave unset to use Codex app-server defaults." },
        sandbox: {
          type: "string",
          enum: ["read_only", "workspace_write"],
          default: "read_only",
          description: "Filesystem permission for this Codex turn.",
        },
        timeoutMs: { type: "integer", minimum: 10000, maximum: 1800000, default: 300000 },
        memoryIds: { type: "array", items: { type: "string" }, description: "Internal HER memory ids to resolve and inject into the Codex prompt." },
      },
      ["prompt"],
    ),
  },
  {
    type: "function",
    name: "coding_agent_start",
    description: "Start an asynchronous Codex coding-agent task in an isolated git worktree. This requires user confirmation by default.",
    parameters: objectSchema(
      {
        prompt: { type: "string", description: "The coding task to run." },
        repoPath: { type: "string", description: "Git repository path. Defaults to HER's current project directory." },
        mode: { type: "string", enum: ["plan", "review", "patch", "test_fix"], default: "plan" },
        timeoutMs: { type: "integer", minimum: 10000, maximum: 1800000, default: 300000 },
      },
      ["prompt"],
    ),
  },
  {
    type: "function",
    name: "coding_agent_status",
    description: "Read one Codex coding-agent task status and recent events.",
    parameters: objectSchema({ taskId: { type: "string" } }, ["taskId"]),
  },
  {
    type: "function",
    name: "coding_agent_continue",
    description: "Continue a completed or failed Codex coding-agent task in the same isolated worktree. This requires confirmation by default.",
    parameters: objectSchema(
      {
        taskId: { type: "string" },
        prompt: { type: "string", description: "Follow-up instructions for Codex." },
        timeoutMs: { type: "integer", minimum: 10000, maximum: 1800000, default: 300000 },
      },
      ["taskId", "prompt"],
    ),
  },
  {
    type: "function",
    name: "coding_agent_cancel",
    description: "Cancel a queued or running Codex coding-agent task.",
    parameters: objectSchema({ taskId: { type: "string" } }, ["taskId"]),
  },
  {
    type: "function",
    name: "coding_agent_get_result",
    description: "Read the final result, worktree path, and branch for a Codex coding-agent task.",
    parameters: objectSchema({ taskId: { type: "string" } }, ["taskId"]),
  },
  {
    type: "function",
    name: "coding_agent_apply_to_repo",
    description: "Apply reviewed Codex worktree file changes back to the original repository. This requires explicit confirmation.",
    parameters: objectSchema(
      {
        taskId: { type: "string", description: "Completed coding-agent task id." },
        paths: { type: "array", items: { type: "string" }, description: "Optional changed file paths to apply. Defaults to all changed files." },
      },
      ["taskId"],
    ),
  },
  {
    type: "function",
    name: "yolo_mode_set",
    description: "Turn YOLO mode on or off. When enabled, HER grants every discovered app permission, enables all global capabilities, and bypasses local confirmation prompts. Only call this when the user explicitly asks for YOLO, no-confirmation, or full-permission mode.",
    parameters: objectSchema(
      {
        enabled: { type: "boolean", description: "true to enable YOLO mode, false to disable it." },
      },
      ["enabled"],
    ),
  },
  {
    type: "function",
    name: "app_permission_search",
    description: "Search locally installed apps and inspect whether they are authorized for HER control. Use before voice authorization when the app name may be ambiguous.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "App name, bundle id, or partial app name. Empty string lists likely apps." },
        limit: { type: "integer", minimum: 1, maximum: 20, default: 8 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "app_permission_set",
    description: "Authorize or revoke a locally installed app for HER control by voice. Only call this when the user explicitly asks to authorize or revoke that app.",
    parameters: objectSchema(
      {
        appName: { type: "string", description: "Visible app name or bundle id, for example YouTube, Google Chrome, or com.google.Chrome." },
        authorized: { type: "boolean", description: "true to authorize, false to revoke authorization." },
      },
      ["appName", "authorized"],
    ),
  },
  {
    type: "function",
    name: "capability_set",
    description: "Turn one of HER's global capability switches on or off by voice.",
    parameters: objectSchema(
      {
        capability: {
          type: "string",
          enum: ["fileManagement", "browserAutomation", "textOperations", "systemOperations"],
          description: "The global capability switch to update.",
        },
        enabled: { type: "boolean" },
      },
      ["capability", "enabled"],
    ),
  },
  {
    type: "function",
    name: "file_list",
    description: "List files in an allowlisted folder such as Desktop, Documents, or Downloads. Read-only.",
    parameters: objectSchema(
      {
        path: { type: "string", description: "Folder path, ~ path, or one of Desktop/Documents/Downloads." },
        includeHidden: { type: "boolean", default: false },
      },
      ["path"],
    ),
  },
  {
    type: "function",
    name: "file_search",
    description: "Search filenames under an allowlisted folder. Read-only.",
    parameters: objectSchema(
      {
        root: { type: "string" },
        query: { type: "string" },
        maxDepth: { type: "integer", minimum: 1, maximum: 8, default: 4 },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 20 },
      },
      ["root", "query"],
    ),
  },
  {
    type: "function",
    name: "file_read",
    description: "Read a small text-like file from an allowlisted folder. Use document_extract for PDF or DOCX.",
    parameters: objectSchema({ path: { type: "string" }, maxChars: { type: "integer", minimum: 100, maximum: 10000, default: 3000 } }, ["path"]),
  },
  {
    type: "function",
    name: "file_open",
    description: "Open a specific allowlisted local file in its default macOS app, or in a named authorized app such as Microsoft Word, Microsoft Excel, Pages, Numbers, Preview, or TextEdit.",
    parameters: objectSchema(
      {
        path: { type: "string", description: "File path, ~ path, or a path under Desktop/Documents/Downloads." },
        appName: { type: "string", description: "Optional app name to force, for example Microsoft Word or Microsoft Excel." },
      },
      ["path"],
    ),
  },
  {
    type: "function",
    name: "file_create_folder",
    description: "Create a new folder inside an allowlisted parent folder such as Desktop, Documents, or Downloads. Requires explicit confirmation.",
    parameters: objectSchema(
      {
        parentPath: { type: "string", description: "Existing allowlisted parent folder, for example Desktop, Documents, Downloads, or ~/Documents/Project." },
        folderName: { type: "string", description: "Name of the new folder only. Do not include slashes." },
      },
      ["parentPath", "folderName"],
    ),
  },
  {
    type: "function",
    name: "file_rename",
    description: "Rename an allowlisted file or folder. Requires explicit confirmation.",
    parameters: objectSchema({ path: { type: "string" }, newName: { type: "string" } }, ["path", "newName"]),
  },
  {
    type: "function",
    name: "file_move",
    description: "Move an allowlisted file or folder to another allowlisted folder. Requires explicit confirmation.",
    parameters: objectSchema({ from: { type: "string" }, to: { type: "string" } }, ["from", "to"]),
  },
  {
    type: "function",
    name: "file_copy",
    description: "Copy an allowlisted file or folder to another allowlisted folder. Requires explicit confirmation.",
    parameters: objectSchema({ from: { type: "string" }, to: { type: "string" } }, ["from", "to"]),
  },
  {
    type: "function",
    name: "file_trash",
    description: "Move an allowlisted file or folder to the user's Trash. Never permanently deletes. Requires explicit confirmation.",
    parameters: objectSchema({ path: { type: "string" } }, ["path"]),
  },
  {
    type: "function",
    name: "document_extract",
    description: "Extract text from .txt, .md, .pdf, or .docx in an allowlisted folder so the assistant can summarize or analyze it.",
    parameters: objectSchema({ path: { type: "string" }, maxChars: { type: "integer", minimum: 500, maximum: 10000, default: 3000 } }, ["path"]),
  },
  {
    type: "function",
    name: "document_folder_digest",
    description: "Extract short text previews from supported documents in a folder, useful for risk review across contracts.",
    parameters: objectSchema(
      {
        root: { type: "string" },
        query: { type: "string", description: "Optional filename filter." },
        limit: { type: "integer", minimum: 1, maximum: 5, default: 3 },
        charsPerFile: { type: "integer", minimum: 300, maximum: 2000, default: 1000 },
      },
      ["root"],
    ),
  },
  {
    type: "function",
    name: "document_prepare_edit",
    description: "Prepare a full replacement edit for a text or markdown file and show a diff preview. Requires confirmation before writing.",
    parameters: objectSchema({ path: { type: "string" }, newContent: { type: "string" } }, ["path", "newContent"]),
  },
  {
    type: "function",
    name: "email_search",
    description: "Search indexed email metadata. This MVP uses the local adapter until Gmail or Microsoft Graph is configured.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "Natural language email search query." },
        limit: { type: "integer", minimum: 1, maximum: 10, default: 5 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "email_read",
    description: "Read a full local email or draft by id after email_search returns a match. Read-only.",
    parameters: objectSchema(
      {
        emailId: { type: "string", description: "Email or draft id returned by email_search." },
      },
      ["emailId"],
    ),
  },
  {
    type: "function",
    name: "email_draft",
    description: "Create a local HER email draft record. This does not appear in Mail.app and never sends email.",
    parameters: objectSchema(
      {
        to: { type: "string" },
        subject: { type: "string" },
        body: { type: "string" },
      },
      ["to", "subject", "body"],
    ),
  },
  {
    type: "function",
    name: "email_send",
    description: "Send a previously created email draft. This always requires explicit user confirmation.",
    parameters: objectSchema({ draftId: { type: "string" } }, ["draftId"]),
  },
  {
    type: "function",
    name: "mac_mail_draft_create",
    description: "Create a visible draft compose window in macOS Mail.app. This never sends email and requires explicit confirmation.",
    parameters: objectSchema(
      {
        to: { type: "string", description: "Recipient email address." },
        subject: { type: "string" },
        body: { type: "string" },
      },
      ["to", "subject", "body"],
    ),
  },
  {
    type: "function",
    name: "calendar_search",
    description: "Search calendar events. This MVP uses the local adapter until Google Calendar or Microsoft Graph is configured.",
    parameters: objectSchema(
      {
        from: { type: "string", description: "ISO date/time lower bound." },
        to: { type: "string", description: "ISO date/time upper bound." },
        query: { type: "string", description: "Optional natural language filter." },
        limit: { type: "integer", minimum: 1, maximum: 20, default: 10 },
      },
      ["from", "to"],
    ),
  },
  {
    type: "function",
    name: "weather_lookup",
    description: "Look up current 7-day weather forecast for a location using HER's local no-key weather adapter.",
    parameters: objectSchema(
      {
        location: { type: "string", description: "City, address, or place name, for example Los Angeles or 上海." },
        date: { type: "string", description: "Optional target date or ISO date/time. Defaults to today." },
      },
      ["location"],
    ),
  },
  {
    type: "function",
    name: "calendar_create",
    description: "Create a calendar event. Title/start/end are the main fields; location, notes, and attendees can default empty. This always requires explicit user confirmation.",
    parameters: objectSchema(
      {
        title: { type: "string" },
        start: { type: "string", description: "ISO date/time." },
        end: { type: "string", description: "ISO date/time." },
        attendees: { type: "array", items: { type: "string" }, default: [] },
        location: { type: "string" },
        notes: { type: "string" },
      },
      ["title", "start", "end"],
    ),
  },
  {
    type: "function",
    name: "mac_calendar_create",
    description: "Create a native macOS Calendar event through AppleScript. Title/start/end are the main fields; calendar name, location, notes, and attendees can default empty. This always requires explicit user confirmation.",
    parameters: objectSchema(
      {
        title: { type: "string" },
        start: { type: "string", description: "ISO date/time." },
        end: { type: "string", description: "ISO date/time." },
        calendarName: { type: "string", description: "Optional target Calendar name. Defaults to the first available calendar." },
        location: { type: "string" },
        notes: { type: "string" },
        attendees: { type: "array", items: { type: "string" }, default: [] },
      },
      ["title", "start", "end"],
    ),
  },
  {
    type: "function",
    name: "mac_reminder_create",
    description: "Create a native macOS Reminders item through AppleScript. This always requires explicit user confirmation.",
    parameters: objectSchema(
      {
        title: { type: "string" },
        dueAt: { type: "string", description: "Optional ISO reminder date/time." },
        listName: { type: "string", description: "Optional Reminders list name. Defaults to the default list." },
        notes: { type: "string" },
      },
      ["title"],
    ),
  },
  {
    type: "function",
    name: "mac_note_create",
    description: "Create a native macOS Notes note through AppleScript. This always requires explicit user confirmation.",
    parameters: objectSchema(
      {
        title: { type: "string" },
        body: { type: "string" },
        folderName: { type: "string", description: "Optional Notes folder name. Defaults to the default folder." },
      },
      ["title", "body"],
    ),
  },
  {
    type: "function",
    name: "copy_search",
    description: "Search local copywriting drafts and snippets.",
    parameters: objectSchema(
      {
        query: { type: "string" },
        limit: { type: "integer", minimum: 1, maximum: 10, default: 5 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "copy_save_draft",
    description: "Save a copywriting draft locally.",
    parameters: objectSchema(
      {
        title: { type: "string" },
        body: { type: "string" },
        project: { type: "string" },
      },
      ["title", "body"],
    ),
  },
  {
    type: "function",
    name: "copy_publish",
    description: "Publish a copywriting draft. This always requires explicit user confirmation.",
    parameters: objectSchema({ draftId: { type: "string" } }, ["draftId"]),
  },
  {
    type: "function",
    name: "music_open",
    description: "Open the macOS Music app.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "music_play_song",
    description: "Play a requested song in macOS Music. Searches the local Music library first; if not found, uses Apple Music catalog lookup to find the song, then sends Music a play command.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "Song title, artist, album, or natural language music request." },
        artist: { type: "string", description: "Optional artist name to narrow the search." },
        mode: { type: "string", enum: ["play", "search"], description: "Use search when the user asks to open, find, or show search results instead of starting playback." },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "music_playback_state",
    description: "Read compact playback state from the macOS Music app.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "music_spotify_search",
    description: "Search Spotify tracks using the official Spotify Web API. Requires HER_SPOTIFY_ACCESS_TOKEN.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "Song title, artist, album, or natural language music request." },
        artist: { type: "string", description: "Optional artist name to narrow the search." },
        limit: { type: "integer", minimum: 1, maximum: 10, default: 5 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "music_spotify_play",
    description: "Play a Spotify track using official Spotify Web API search and playback. Requires OAuth scopes, Premium eligibility, and an active device.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "Song title, artist, album, or natural language music request." },
        artist: { type: "string", description: "Optional artist name to narrow the search." },
        deviceId: { type: "string", description: "Optional Spotify device id. If omitted, HER uses HER_SPOTIFY_DEVICE_ID or the first active device." },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "music_spotify_playback_state",
    description: "Read current Spotify playback state using the official Spotify Web API.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "music_netease_open",
    description: "Open NetEase Cloud Music client or official search page. This does not claim direct playback.",
    parameters: objectSchema({
      query: { type: "string", description: "Optional song, artist, or playlist query to open in NetEase Cloud Music web search." },
      url: { type: "string", description: "Optional direct NetEase Cloud Music URL to open." },
    }),
  },
  {
    type: "function",
    name: "music_qq_open",
    description: "Open QQ Music client or QQ Music official web search page. This does not claim direct playback or bypass login/VIP/copyright restrictions.",
    parameters: objectSchema({
      query: { type: "string", description: "Optional song, artist, album, or playlist query to open in QQ Music search." },
      target: { type: "string", enum: ["app", "web"], default: "web", description: "Open the QQ Music client or web search page. App mode requires the client to be installed." },
    }),
  },
  {
    type: "function",
    name: "media_key_control",
    description: "Send a basic media control keystroke such as play/pause, next, previous, volume up, or volume down. Works best after focusing a media app such as QQ Music.",
    parameters: objectSchema(
      {
        action: { type: "string", enum: ["play_pause", "next", "previous", "volume_up", "volume_down"] },
        appName: { type: "string", description: "Optional app to focus before sending the keystroke, for example QQMusic or Music." },
      },
      ["action"],
    ),
  },
  {
    type: "function",
    name: "video_play",
    description: "Play or open a video by title or URL. YouTube uses official Data API search when HER_YOUTUBE_API_KEY is configured and isolated Chrome playback. Bilibili opens search/video pages and browser-level playback only. Apple TV uses search/catalog URLs.",
    parameters: objectSchema(
      {
        service: { type: "string", enum: ["youtube", "apple_tv", "bilibili"], description: "Video service to use." },
        query: { type: "string", description: "Video title, movie/show name, episode name, or a direct video URL." },
        mode: { type: "string", enum: ["play", "search"], description: "Use search to show results instead of opening or attempting playback of the first resolved item." },
      },
      ["service", "query"],
    ),
  },
  {
    type: "function",
    name: "video_playback_control",
    description: "Control or read the active video element in HER's isolated Chrome window. Useful for YouTube and Bilibili playback after opening a page.",
    parameters: objectSchema(
      {
        action: { type: "string", enum: ["play", "pause", "toggle", "state"] },
      },
      ["action"],
    ),
  },
  {
    type: "function",
    name: "apple_tv_playback_state",
    description: "Read compact playback state from the macOS TV app. Apple TV exposes limited state and may not identify the requested catalog item.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "social_x_search",
    description: "Read/search recent posts using the official X API v2. Requires HER_X_BEARER_TOKEN and is subject to X access tier limits.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "X API recent-search query." },
        limit: { type: "integer", minimum: 10, maximum: 100, default: 10 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "social_x_post",
    description: "Create a post on X using the official X API v2. Requires explicit confirmation and a user-context token with write permission.",
    parameters: objectSchema(
      {
        text: { type: "string", minLength: 1, maxLength: 280 },
        replyToTweetId: { type: "string", description: "Optional tweet id to reply to." },
      },
      ["text"],
    ),
  },
  {
    type: "function",
    name: "social_open",
    description: "Open a social media page without sensitive automation. For Xiaohongshu, only open search, note, or share pages.",
    parameters: objectSchema(
      {
        service: { type: "string", enum: ["x", "xiaohongshu"] },
        kind: { type: "string", enum: ["home", "search", "profile", "note", "share"], default: "search" },
        target: { type: "string", description: "Search query, profile handle, note/share id, or URL." },
        isolated: { type: "boolean", default: true },
      },
      ["service"],
    ),
  },
  {
    type: "function",
    name: "news_search",
    description: "Search news using a configured provider and return structured results for a popup display. GDELT is keyless but rate-limited; NewsAPI requires HER_NEWS_API_KEY.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "News search query." },
        provider: { type: "string", enum: ["gdelt", "newsapi"], default: "gdelt" },
        limit: { type: "integer", minimum: 1, maximum: 25, default: 8 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "sec_filing_search",
    description: "Search recent SEC EDGAR filings for a ticker, company name, or CIK and return structured results for a popup display.",
    parameters: objectSchema(
      {
        company: { type: "string", description: "Ticker, company name, or CIK, for example AAPL or 0000320193." },
        forms: { type: "array", items: { type: "string" }, default: [], description: "Optional SEC forms to include, such as 10-K, 10-Q, 8-K, 4." },
        limit: { type: "integer", minimum: 1, maximum: 30, default: 10 },
      },
      ["company"],
    ),
  },
  {
    type: "function",
    name: "macro_series_lookup",
    description: "Read an official macroeconomic time series from BLS Public Data API and return structured results for a popup display.",
    parameters: objectSchema(
      {
        seriesId: { type: "string", description: "BLS series id, for example CUSR0000SA0 for CPI-U all items." },
        startYear: { type: "string", description: "Optional start year." },
        endYear: { type: "string", description: "Optional end year." },
      },
      ["seriesId"],
    ),
  },
  {
    type: "function",
    name: "market_quote_lookup",
    description: "Read a market quote from Alpha Vantage and return structured results for a popup display. Requires HER_ALPHA_VANTAGE_API_KEY for non-demo use.",
    parameters: objectSchema(
      {
        symbol: { type: "string", description: "Ticker symbol, for example AAPL, MSFT, or IBM." },
      },
      ["symbol"],
    ),
  },
  {
    type: "function",
    name: "shortcut_list",
    description: "List local macOS Shortcuts by name so HER can run an existing user-created shortcut.",
    parameters: objectSchema({ limit: { type: "integer", minimum: 1, maximum: 50, default: 20 } }),
  },
  {
    type: "function",
    name: "shortcut_run",
    description: "Run an existing macOS Shortcut by name. Use for user-created media or app actions, then verify media playback with state tools when relevant. Requires explicit confirmation.",
    parameters: objectSchema(
      {
        name: { type: "string", description: "Shortcut name or identifier." },
        input: { type: "string", description: "Optional plain text input written to a temporary input file for the shortcut." },
        timeoutMs: { type: "integer", minimum: 1000, maximum: 180000, default: 60000 },
      },
      ["name"],
    ),
  },
  {
    type: "function",
    name: "contacts_search",
    description: "Search local macOS Contacts for a person or phone number before calling. Returns compact masked phone matches.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "Person name or phone number to search." },
        limit: { type: "integer", minimum: 1, maximum: 10, default: 5 },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "phone_call",
    description: "Start a phone or FaceTime audio call using macOS tel:/facetime-audio: URL handling. This always requires explicit user confirmation.",
    parameters: objectSchema(
      {
        phoneNumber: { type: "string", description: "Phone number to call." },
        contactName: { type: "string", description: "Optional contact name for confirmation and audit." },
        mode: { type: "string", enum: ["phone", "facetime_audio", "facetime_video"], default: "phone" },
      },
      ["phoneNumber"],
    ),
  },
  {
    type: "function",
    name: "app_open",
    description: "Open a user-authorized macOS app by name.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "app_focus",
    description: "Bring a user-authorized macOS app to the front.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "app_quit",
    description: "Quit a user-authorized macOS app. Requires explicit confirmation.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "window_list",
    description: "List visible windows for authorized apps. Requires system operations capability and Accessibility permission.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "window_close_all",
    description: "Close all visible windows for authorized apps in one action. Skips HER/Electron itself so the assistant remains available. Requires explicit confirmation unless YOLO mode is enabled.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "window_hide_all",
    description: "Hide visible app windows directly with macOS System Events. Use for hide all, clear view, or keep only the current/frontmost app visible. Does not use Codex.",
    parameters: objectSchema({
      preserveFrontmost: {
        type: "boolean",
        default: false,
        description: "Keep the current frontmost app visible and hide the rest.",
      },
      preserveFinder: {
        type: "boolean",
        default: true,
        description: "Keep Finder visible. Defaults to true.",
      },
    }),
  },
  {
    type: "function",
    name: "window_minimize_all",
    description: "Minimize all visible authorized app windows into the Dock using Accessibility. Does not use Codex.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "window_auto_arrange",
    description: "Automatically arrange visible windows for authorized apps into a grid on the current desktop. Use when the user asks to auto-arrange, tile, organize, or lay out windows.",
    parameters: objectSchema({
      appNames: {
        type: "array",
        items: { type: "string" },
        description: "Optional app names to arrange. Omit to arrange all visible authorized app windows.",
      },
    }),
  },
  {
    type: "function",
    name: "window_minimize_unrelated",
    description: "Keep task-related windows visible and minimize other visible windows for authorized apps. Use when the user asks to keep current task windows and minimize everything else.",
    parameters: objectSchema({
      keepAppNames: {
        type: "array",
        items: { type: "string" },
        description: "Apps that should remain visible because they are related to the current task.",
      },
      keepTitleKeywords: {
        type: "array",
        items: { type: "string" },
        description: "Case-insensitive title keywords for windows that should remain visible.",
      },
      preserveFrontmost: {
        type: "boolean",
        default: true,
        description: "Also keep the current frontmost window visible. Defaults to true.",
      },
    }),
  },
  {
    type: "function",
    name: "window_close",
    description: "Close the front window of a user-authorized app. Requires explicit confirmation.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "window_minimize",
    description: "Minimize the front window of a user-authorized app.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "window_maximize",
    description: "Zoom or maximize the front window of a user-authorized app.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "window_move_resize",
    description: "Move and resize the front window of a user-authorized app.",
    parameters: objectSchema(
      {
        appName: { type: "string" },
        x: { type: "integer" },
        y: { type: "integer" },
        width: { type: "integer", minimum: 120 },
        height: { type: "integer", minimum: 120 },
      },
      ["appName", "x", "y", "width", "height"],
    ),
  },
  {
    type: "function",
    name: "desktop_show",
    description: "Trigger macOS Show Desktop directly using System Events. Does not use Codex.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "desktop_open_app",
    description: "Open an allowlisted macOS app.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "system_close_app",
    description: "Quit an allowlisted macOS app. Requires explicit confirmation.",
    parameters: objectSchema({ appName: { type: "string" } }, ["appName"]),
  },
  {
    type: "function",
    name: "system_sleep",
    description: "Put the Mac to sleep using the macOS pmset command. Requires explicit confirmation.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "system_lock_screen",
    description: "Lock or display-sleep the Mac using the macOS pmset command. Requires explicit confirmation.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "system_set_volume",
    description: "Set macOS output volume from 0 to 100. Requires explicit confirmation.",
    parameters: objectSchema({ level: { type: "integer", minimum: 0, maximum: 100 } }, ["level"]),
  },
  {
    type: "function",
    name: "system_get_volume",
    description: "Read current macOS output volume and mute state.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "system_mute_volume",
    description: "Mute or unmute macOS output volume.",
    parameters: objectSchema({ muted: { type: "boolean" } }, ["muted"]),
  },
  {
    type: "function",
    name: "system_set_brightness",
    description: "Set display brightness from 0 to 100 if a local brightness CLI is installed. Requires explicit confirmation.",
    parameters: objectSchema({ level: { type: "integer", minimum: 0, maximum: 100 } }, ["level"]),
  },
  {
    type: "function",
    name: "system_set_dark_mode",
    description: "Turn macOS dark mode on or off. Requires explicit confirmation.",
    parameters: objectSchema({ enabled: { type: "boolean" } }, ["enabled"]),
  },
  {
    type: "function",
    name: "system_open_settings",
    description: "Open a safe System Settings pane. Does not change settings by itself.",
    parameters: objectSchema({ pane: { type: "string", description: "Optional pane name such as displays, sound, bluetooth, keyboard, privacy, accessibility, screenRecording, automation, or fullDiskAccess." } }),
  },
  {
    type: "function",
    name: "desktop_clipboard_write",
    description: "Write text to the system clipboard. This always requires explicit user confirmation.",
    parameters: objectSchema({ text: { type: "string" } }, ["text"]),
  },
  {
    type: "function",
    name: "desktop_clipboard_read",
    description: "Read plain text from the system clipboard.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "system_speak",
    description: "Speak text through the macOS say command.",
    parameters: objectSchema({
      text: { type: "string" },
      voice: { type: "string", description: "Optional macOS voice name, such as Tingting." },
    }, ["text"]),
  },
  {
    type: "function",
    name: "system_notification",
    description: "Show a macOS notification or confirmation dialog through AppleScript.",
    parameters: objectSchema({
      title: { type: "string" },
      message: { type: "string" },
      dialog: { type: "boolean", default: false },
    }, ["title", "message"]),
  },
  {
    type: "function",
    name: "screenshot_capture",
    description: "Take a screenshot to the clipboard, Desktop, or interactive selection using screencapture.",
    parameters: objectSchema({
      mode: { type: "string", enum: ["clipboard", "desktop", "selection"] },
    }, ["mode"]),
  },
  {
    type: "function",
    name: "keyboard_shortcut",
    description: "Send a small allowlisted keyboard shortcut to the frontmost app, such as copy, paste, new tab, refresh, escape, or enter.",
    parameters: objectSchema({
      action: { type: "string", enum: ["copy", "paste", "select_all", "undo", "enter", "escape", "tab", "new_window", "new_tab", "refresh", "browser_back", "browser_forward", "toggle_fullscreen"] },
    }, ["action"]),
  },
  {
    type: "function",
    name: "browser_open_url",
    description: "Open an allowlisted URL in the default browser.",
    parameters: objectSchema({ url: { type: "string" } }, ["url"]),
  },
  {
    type: "function",
    name: "browser_search_open",
    description: "Open a browser search results page without reading or returning search result content.",
    parameters: objectSchema(
      {
        query: { type: "string", description: "Search query to open in the browser." },
        engine: { type: "string", enum: ["google", "bing", "duckduckgo"], default: "google" },
        isolated: { type: "boolean", default: true, description: "Open in HER's isolated browser profile unless the user needs existing cookies, login state, or extensions." },
      },
      ["query"],
    ),
  },
  {
    type: "function",
    name: "browser_isolated_open_url",
    description: "Open an allowlisted URL in an isolated Chrome profile with remote debugging for controlled browser automation.",
    parameters: objectSchema({ url: { type: "string" } }, ["url"]),
  },
  {
    type: "function",
    name: "browser_isolated_window_focus",
    description: "Focus and raise HER's isolated Chrome window by its dedicated profile process.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "browser_isolated_window_move_resize",
    description: "Move and resize HER's isolated Chrome window by its dedicated profile process.",
    parameters: objectSchema(
      {
        x: { type: "integer" },
        y: { type: "integer" },
        width: { type: "integer", minimum: 120 },
        height: { type: "integer", minimum: 120 },
      },
      ["x", "y", "width", "height"],
    ),
  },
  {
    type: "function",
    name: "browser_read_page",
    description: "Read compact page state from HER's isolated browser: current URL, title, visible text excerpt, links, and form fields. Read-only.",
    parameters: objectSchema({ maxChars: { type: "integer", minimum: 200, maximum: 10000, default: 3000 } }),
  },
  {
    type: "function",
    name: "browser_read_video_state",
    description: "Read compact playback state from the active video element in HER's isolated browser.",
    parameters: objectSchema({}),
  },
  {
    type: "function",
    name: "browser_fill_form",
    description: "Fill form fields in the isolated browser using CSS selectors. Requires explicit confirmation.",
    parameters: objectSchema(
      {
        fields: {
          type: "array",
          items: objectSchema({ selector: { type: "string" }, value: { type: "string" } }, ["selector", "value"]),
        },
      },
      ["fields"],
    ),
  },
  {
    type: "function",
    name: "browser_click",
    description: "Click a CSS selector in the isolated browser. Submitting, paying, deleting, or publishing must be confirmed.",
    parameters: objectSchema(
      {
        selector: { type: "string" },
        purpose: { type: "string", description: "What this click is expected to do." },
      },
      ["selector", "purpose"],
    ),
  },
  {
    type: "function",
    name: "advanced_shell_command",
    description: "Run an advanced local shell command after safety checks and explicit confirmation. Dangerous commands are blocked.",
    parameters: objectSchema(
      {
        command: { type: "string" },
        reason: { type: "string", description: "Why this command is needed." },
        timeoutMs: { type: "integer", minimum: 1000, maximum: 20000, default: 10000 },
      },
      ["command", "reason"],
    ),
  },
] as const;

export type ToolName = (typeof allToolDefinitions)[number]["name"];

const limitSchema = z.number().int().min(1).max(10).optional().default(5);
const folderNameSchema = z.string().min(1).refine(
  (value) => {
    const trimmed = value.trim();
    return Boolean(trimmed) && trimmed !== "." && trimmed !== ".." && !trimmed.includes("/") && !trimmed.includes("\\");
  },
  { message: "folderName must be a valid folder name without slashes." },
);

export const toolSchemas: Record<ToolName, z.ZodTypeAny> = {
  system_status: z.object({}),
  confirmation_list: z.object({}),
  confirmation_decide: z.object({ confirmationId: z.string().min(1).optional(), approved: z.boolean() }),
  tool_result_read: z.object({
    handle: z.string().min(1),
    offset: z.number().int().min(0).optional().default(0),
    maxChars: z.number().int().min(200).max(6000).optional().default(2000),
  }),
  tool_catalog_list: z.object({ group: z.enum(toolGroups).optional() }),
  tool_group_set: z.object({ group: z.enum(toolGroups), enabled: z.boolean() }),
  her_select_bundle: z.object({ transcript: z.string().min(1) }),
  task_create: z.object({
    toolName: z.string().min(1),
    arguments: z.record(z.string(), z.unknown()).optional().default({}),
    priority: z.enum(["low", "normal", "high"]).optional().default("normal"),
    runAfterMs: z.number().int().min(0).max(600000).optional().default(0),
  }),
  task_status: z.object({ taskId: z.string().min(1) }),
  task_list: z.object({
    status: z.enum(["queued", "running", "awaiting_confirmation", "blocked", "completed", "failed", "cancelled", "needs_confirmation"]).optional(),
    limit: z.number().int().min(1).max(30).optional().default(10),
  }),
  task_cancel: z.object({ taskId: z.string().min(1) }),
  task_events: z.object({ taskId: z.string().min(1), limit: z.number().int().min(1).max(100).optional().default(50) }),
  task_route: z.object({
    userRequest: z.string().min(1),
    preference: z.enum(["auto", "native", "search", "codex"]).optional().default("auto"),
    cwd: z.string().min(1).optional(),
    activeApp: z.string().min(1).optional(),
    selectedText: z.string().optional(),
  }),
  intent_route: z.object({
    intent: z.object({
      originalText: z.string().min(1),
      intent: z.string().min(1),
      complexity: z.enum(["simple", "complex", "ambiguous"]),
      domain: z.enum([
        "desktop",
        "apps",
        "windows",
        "system",
        "media",
        "social",
        "research",
        "calendar",
        "reminder",
        "notes",
        "weather",
        "travel",
        "browser",
        "files",
        "documents",
        "email",
        "coding",
        "research",
        "phone",
        "memory",
        "unknown",
      ]),
      action: z.string().optional(),
      entities: z.record(z.string(), z.unknown()).optional().default({}),
      toolName: z.string().optional(),
      toolArguments: z.record(z.string(), z.unknown()).optional().default({}),
      candidateTools: z.array(z.string()).optional().default([]),
      missingInfo: z.array(z.string()).optional().default([]),
      confidence: z.number().min(0).max(1),
      routePreference: z.enum(["auto", "direct", "codex", "clarify"]).optional().default("auto"),
    }),
    cwd: z.string().min(1).optional(),
    activeApp: z.string().min(1).optional(),
    selectedText: z.string().optional(),
  }),
  memory_lookup: z.object({
    query: z.string().min(1),
    types: z.array(z.enum(["path_alias", "preference", "task_template"])).optional(),
    limit: z.number().int().min(1).max(10).optional().default(5),
  }),
  memory_save: z.object({
    type: z.enum(["path_alias", "preference", "task_template"]),
    key: z.string().min(1),
    value: z.string().optional(),
    summary: z.string().optional(),
    content: z.string().optional(),
    aliases: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
  memory_forget: z.object({ idOrKey: z.string().min(1) }),
  memory_status: z.object({}),
  alias_create: z.object({
    phrase: z.string().min(1),
    toolName: z.string().min(1),
    arguments: z.record(z.string(), z.unknown()).optional().default({}),
    description: z.string().optional(),
    overwrite: z.boolean().optional().default(false),
  }),
  alias_list: z.object({ query: z.string().optional() }),
  alias_delete: z.object({
    aliasId: z.string().min(1).optional(),
    phrase: z.string().min(1).optional(),
  }).refine((value) => Boolean(value.aliasId || value.phrase), {
    message: "aliasId or phrase is required",
  }),
  codex_task_run: z.object({
    prompt: z.string().min(1),
    cwd: z.string().min(1).optional(),
    model: z.string().min(1).optional(),
    sandbox: z.enum(["read_only", "workspace_write"]).optional().default("read_only"),
    timeoutMs: z.number().int().min(10000).max(1800000).optional().default(config.codexTurnTimeoutMs),
    memoryIds: z.array(z.string()).optional().default([]),
  }),
  coding_agent_start: z.object({
    prompt: z.string().min(1),
    repoPath: z.string().min(1).optional(),
    mode: z.enum(["plan", "review", "patch", "test_fix"]).optional().default("plan"),
    timeoutMs: z.number().int().min(10000).max(1800000).optional().default(config.codexTurnTimeoutMs),
  }),
  coding_agent_status: z.object({ taskId: z.string().min(1) }),
  coding_agent_continue: z.object({
    taskId: z.string().min(1),
    prompt: z.string().min(1),
    timeoutMs: z.number().int().min(10000).max(1800000).optional().default(config.codexTurnTimeoutMs),
  }),
  coding_agent_cancel: z.object({ taskId: z.string().min(1) }),
  coding_agent_get_result: z.object({ taskId: z.string().min(1) }),
  coding_agent_apply_to_repo: z.object({
    taskId: z.string().min(1),
    paths: z.array(z.string().min(1)).optional(),
  }),
  yolo_mode_set: z.object({ enabled: z.boolean() }),
  file_list: z.object({ path: z.string().min(1), includeHidden: z.boolean().optional().default(false) }),
  file_search: z.object({ root: z.string().min(1), query: z.string(), maxDepth: z.number().int().min(1).max(8).optional().default(4), limit: z.number().int().min(1).max(50).optional().default(20) }),
  file_read: z.object({ path: z.string().min(1), maxChars: z.number().int().min(100).max(10000).optional().default(3000) }),
  file_open: z.object({ path: z.string().min(1), appName: z.string().min(1).optional() }),
  file_create_folder: z.object({ parentPath: z.string().min(1), folderName: folderNameSchema }),
  file_rename: z.object({ path: z.string().min(1), newName: z.string().min(1) }),
  file_move: z.object({ from: z.string().min(1), to: z.string().min(1) }),
  file_copy: z.object({ from: z.string().min(1), to: z.string().min(1) }),
  file_trash: z.object({ path: z.string().min(1) }),
  document_extract: z.object({ path: z.string().min(1), maxChars: z.number().int().min(500).max(10000).optional().default(3000) }),
  document_folder_digest: z.object({ root: z.string().min(1), query: z.string().optional(), limit: z.number().int().min(1).max(5).optional().default(3), charsPerFile: z.number().int().min(300).max(2000).optional().default(1000) }),
  document_prepare_edit: z.object({ path: z.string().min(1), newContent: z.string() }),
  email_search: z.object({ query: z.string().min(1), limit: limitSchema }),
  email_read: z.object({ emailId: z.string().min(1) }),
  email_draft: z.object({ to: z.string().min(1), subject: z.string().min(1), body: z.string().min(1) }),
  email_send: z.object({ draftId: z.string().min(1) }),
  mac_mail_draft_create: z.object({ to: z.string().email(), subject: z.string().min(1), body: z.string().min(1) }),
  weather_lookup: z.object({ location: z.string().min(1), date: z.string().min(1).optional() }),
  calendar_search: z.object({ from: z.string().min(1), to: z.string().min(1), query: z.string().optional(), limit: z.number().int().min(1).max(20).optional().default(10) }),
  calendar_create: z.object({
    title: z.string().min(1),
    start: z.string().min(1),
    end: z.string().min(1),
    attendees: z.array(z.string()).optional().default([]),
    location: z.string().optional(),
    notes: z.string().optional(),
  }),
  mac_calendar_create: z.object({
    title: z.string().min(1),
    start: z.string().min(1),
    end: z.string().min(1),
    calendarName: z.string().min(1).optional(),
    location: z.string().optional(),
    notes: z.string().optional(),
    attendees: z.array(z.string()).optional().default([]),
  }),
  mac_reminder_create: z.object({
    title: z.string().min(1),
    dueAt: z.string().min(1).optional(),
    listName: z.string().min(1).optional(),
    notes: z.string().optional(),
  }),
  mac_note_create: z.object({
    title: z.string().min(1),
    body: z.string().min(1),
    folderName: z.string().min(1).optional(),
  }),
  copy_search: z.object({ query: z.string().min(1), limit: limitSchema }),
  copy_save_draft: z.object({ title: z.string().min(1), body: z.string().min(1), project: z.string().optional() }),
  copy_publish: z.object({ draftId: z.string().min(1) }),
  music_open: z.object({}),
  music_play_song: z.object({ query: z.string().min(1), artist: z.string().optional(), mode: z.enum(["play", "search"]).optional().default("play") }),
  music_playback_state: z.object({}),
  music_spotify_search: z.object({ query: z.string().min(1), artist: z.string().optional(), limit: z.number().int().min(1).max(10).optional().default(5) }),
  music_spotify_play: z.object({ query: z.string().min(1), artist: z.string().optional(), deviceId: z.string().min(1).optional() }),
  music_spotify_playback_state: z.object({}),
  music_netease_open: z.object({ query: z.string().min(1).optional(), url: z.string().url().optional() }),
  music_qq_open: z.object({ query: z.string().min(1).optional(), target: z.enum(["app", "web"]).optional().default("web") }),
  media_key_control: z.object({ action: z.enum(["play_pause", "next", "previous", "volume_up", "volume_down"]), appName: z.string().min(1).optional() }),
  video_play: z.object({ service: z.enum(["youtube", "apple_tv", "bilibili"]), query: z.string().min(1), mode: z.enum(["play", "search"]).optional().default("play") }),
  video_playback_control: z.object({ action: z.enum(["play", "pause", "toggle", "state"]) }),
  apple_tv_playback_state: z.object({}),
  social_x_search: z.object({ query: z.string().min(1), limit: z.number().int().min(10).max(100).optional().default(10) }),
  social_x_post: z.object({ text: z.string().min(1).max(280), replyToTweetId: z.string().min(1).optional() }),
  social_open: z.object({
    service: z.enum(["x", "xiaohongshu"]),
    kind: z.enum(["home", "search", "profile", "note", "share"]).optional().default("search"),
    target: z.string().optional(),
    isolated: z.boolean().optional().default(true),
  }),
  news_search: z.object({
    query: z.string().min(1),
    provider: z.enum(["gdelt", "newsapi"]).optional().default("gdelt"),
    limit: z.number().int().min(1).max(25).optional().default(8),
  }),
  sec_filing_search: z.object({
    company: z.string().min(1),
    forms: z.array(z.string().min(1)).optional().default([]),
    limit: z.number().int().min(1).max(30).optional().default(10),
  }),
  macro_series_lookup: z.object({
    seriesId: z.string().min(1),
    startYear: z.string().min(4).max(4).optional(),
    endYear: z.string().min(4).max(4).optional(),
  }),
  market_quote_lookup: z.object({ symbol: z.string().min(1) }),
  shortcut_list: z.object({ limit: z.number().int().min(1).max(50).optional().default(20) }),
  shortcut_run: z.object({
    name: z.string().min(1),
    input: z.string().optional(),
    timeoutMs: z.number().int().min(1000).max(180000).optional().default(60000),
  }),
  contacts_search: z.object({ query: z.string().min(1), limit: z.number().int().min(1).max(10).optional().default(5) }),
  phone_call: z.object({
    phoneNumber: z.string().min(1),
    contactName: z.string().min(1).optional(),
    mode: z.enum(["phone", "facetime_audio", "facetime_video"]).optional().default("phone"),
  }),
  app_open: z.object({ appName: z.string().min(1) }),
  app_focus: z.object({ appName: z.string().min(1) }),
  app_quit: z.object({ appName: z.string().min(1) }),
  window_list: z.object({}),
  window_close_all: z.object({}),
  window_hide_all: z.object({
    preserveFrontmost: z.boolean().optional().default(false),
    preserveFinder: z.boolean().optional().default(true),
  }),
  window_minimize_all: z.object({}),
  window_auto_arrange: z.object({ appNames: z.array(z.string().min(1)).optional().default([]) }),
  window_minimize_unrelated: z.object({
    keepAppNames: z.array(z.string().min(1)).optional().default([]),
    keepTitleKeywords: z.array(z.string().min(1)).optional().default([]),
    preserveFrontmost: z.boolean().optional().default(true),
  }),
  window_close: z.object({ appName: z.string().min(1) }),
  window_minimize: z.object({ appName: z.string().min(1) }),
  window_maximize: z.object({ appName: z.string().min(1) }),
  window_move_resize: z.object({
    appName: z.string().min(1),
    x: z.number().int(),
    y: z.number().int(),
    width: z.number().int().min(120),
    height: z.number().int().min(120),
  }),
  desktop_show: z.object({}),
  desktop_open_app: z.object({ appName: z.string().min(1) }),
  system_close_app: z.object({ appName: z.string().min(1) }),
  system_sleep: z.object({}),
  system_lock_screen: z.object({}),
  system_set_volume: z.object({ level: z.number().int().min(0).max(100) }),
  system_get_volume: z.object({}),
  system_mute_volume: z.object({ muted: z.boolean() }),
  system_set_brightness: z.object({ level: z.number().int().min(0).max(100) }),
  system_set_dark_mode: z.object({ enabled: z.boolean() }),
  system_open_settings: z.object({ pane: z.string().optional() }),
  desktop_clipboard_write: z.object({ text: z.string().min(1) }),
  desktop_clipboard_read: z.object({}),
  system_speak: z.object({ text: z.string().min(1), voice: z.string().min(1).optional() }),
  system_notification: z.object({ title: z.string().min(1), message: z.string().min(1), dialog: z.boolean().optional().default(false) }),
  screenshot_capture: z.object({ mode: z.enum(["clipboard", "desktop", "selection"]) }),
  keyboard_shortcut: z.object({
    action: z.enum(["copy", "paste", "select_all", "undo", "enter", "escape", "tab", "new_window", "new_tab", "refresh", "browser_back", "browser_forward", "toggle_fullscreen"]),
  }),
  browser_open_url: z.object({ url: z.string().url() }),
  browser_search_open: z.object({
    query: z.string().min(1),
    engine: z.enum(["google", "bing", "duckduckgo"]).optional().default("google"),
    isolated: z.boolean().optional().default(true),
  }),
  browser_isolated_open_url: z.object({ url: z.string().url() }),
  browser_isolated_window_focus: z.object({}),
  browser_isolated_window_move_resize: z.object({
    x: z.number().int(),
    y: z.number().int(),
    width: z.number().int().min(120),
    height: z.number().int().min(120),
  }),
  browser_read_page: z.object({ maxChars: z.number().int().min(200).max(10000).optional().default(3000) }),
  browser_read_video_state: z.object({}),
  browser_fill_form: z.object({ fields: z.array(z.object({ selector: z.string().min(1), value: z.string() })).min(1).max(30) }),
  browser_click: z.object({ selector: z.string().min(1), purpose: z.string().min(1) }),
  advanced_shell_command: z.object({ command: z.string().min(1), reason: z.string().min(1), timeoutMs: z.number().int().min(1000).max(20000).optional().default(10000) }),
  app_permission_search: z.object({ query: z.string(), limit: z.number().int().min(1).max(20).optional().default(8) }),
  app_permission_set: z.object({ appName: z.string().min(1), authorized: z.boolean() }),
  capability_set: z.object({ capability: z.enum(["fileManagement", "browserAutomation", "textOperations", "systemOperations"]), enabled: z.boolean() }),
};


export const coreRealtimeToolNames = [
  "system_status",
  "confirmation_list",
  "confirmation_decide",
  "app_permission_search",
  "app_permission_set",
  "capability_set",
  "yolo_mode_set",
  "her_select_bundle",
  "tool_result_read",
  "intent_route",
  "task_status",
  "task_list",
  "task_cancel",
  "task_events",
  "memory_save",
  "memory_forget",
  "memory_status",
] as const satisfies readonly ToolName[];

export const toolGroupByName = {
  codex_task_run: "agents",
  coding_agent_start: "agents",
  coding_agent_status: "agents",
  coding_agent_continue: "agents",
  coding_agent_cancel: "agents",
  coding_agent_get_result: "agents",
  coding_agent_apply_to_repo: "agents",
  yolo_mode_set: "permissions",
  app_permission_search: "permissions",
  app_permission_set: "permissions",
  capability_set: "permissions",
  file_list: "files",
  file_search: "files",
  file_read: "files",
  file_open: "files",
  file_create_folder: "files",
  file_rename: "files",
  file_move: "files",
  file_copy: "files",
  file_trash: "files",
  document_extract: "documents",
  document_folder_digest: "documents",
  document_prepare_edit: "documents",
  email_search: "text",
  email_read: "text",
  email_draft: "text",
  email_send: "text",
  mac_mail_draft_create: "text",
  weather_lookup: "text",
  calendar_search: "text",
  calendar_create: "text",
  mac_calendar_create: "text",
  mac_reminder_create: "text",
  mac_note_create: "text",
  copy_search: "text",
  copy_save_draft: "text",
  copy_publish: "text",
  music_open: "media",
  music_play_song: "media",
  music_playback_state: "media",
  music_spotify_search: "media",
  music_spotify_play: "media",
  music_spotify_playback_state: "media",
  music_netease_open: "media",
  music_qq_open: "media",
  media_key_control: "media",
  video_play: "media",
  video_playback_control: "media",
  apple_tv_playback_state: "media",
  social_x_search: "social",
  social_x_post: "social",
  social_open: "social",
  news_search: "research",
  sec_filing_search: "research",
  macro_series_lookup: "research",
  market_quote_lookup: "research",
  shortcut_list: "media",
  shortcut_run: "media",
  contacts_search: "phone",
  phone_call: "phone",
  app_open: "apps",
  app_focus: "apps",
  app_quit: "apps",
  desktop_open_app: "apps",
  window_list: "windows",
  window_close_all: "windows",
  window_hide_all: "windows",
  window_minimize_all: "windows",
  window_auto_arrange: "windows",
  window_minimize_unrelated: "windows",
  window_close: "windows",
  window_minimize: "windows",
  window_maximize: "windows",
  window_move_resize: "windows",
  desktop_show: "windows",
  system_close_app: "system",
  system_sleep: "system",
  system_lock_screen: "system",
  system_set_volume: "system",
  system_get_volume: "system",
  system_mute_volume: "system",
  system_set_brightness: "system",
  system_set_dark_mode: "system",
  system_open_settings: "system",
  desktop_clipboard_write: "system",
  desktop_clipboard_read: "system",
  system_speak: "system",
  system_notification: "system",
  screenshot_capture: "system",
  keyboard_shortcut: "system",
  browser_open_url: "browser",
  browser_search_open: "browser",
  browser_isolated_open_url: "browser",
  browser_isolated_window_focus: "browser",
  browser_isolated_window_move_resize: "browser",
  browser_read_page: "browser",
  browser_read_video_state: "browser",
  browser_fill_form: "browser",
  browser_click: "browser",
  advanced_shell_command: "shell",
} as const satisfies Partial<Record<ToolName, ToolGroup>>;

export const toolRiskOverrides: Partial<Record<ToolName, ToolRisk>> = {
  alias_create: "local_write",
  alias_delete: "local_write",
  task_cancel: "system_change",
  codex_task_run: "coding_agent",
  coding_agent_start: "coding_agent",
  coding_agent_continue: "coding_agent",
  coding_agent_apply_to_repo: "coding_agent",
  phone_call: "external_send",
  file_open: "local_open",
  file_create_folder: "local_write",
  file_rename: "local_write",
  file_move: "local_write",
  file_copy: "local_write",
  file_trash: "local_write",
  document_prepare_edit: "local_write",
  email_draft: "local_write",
  email_send: "external_send",
  mac_mail_draft_create: "external_send",
  calendar_create: "external_send",
  mac_calendar_create: "external_send",
  mac_reminder_create: "local_write",
  mac_note_create: "local_write",
  copy_save_draft: "local_write",
  copy_publish: "external_send",
  music_open: "local_open",
  music_play_song: "local_open",
  music_spotify_play: "local_open",
  music_netease_open: "local_open",
  music_qq_open: "local_open",
  media_key_control: "local_open",
  video_play: "local_open",
  video_playback_control: "local_open",
  social_x_post: "external_send",
  social_open: "local_open",
  shortcut_run: "system_change",
  app_open: "local_open",
  app_focus: "local_open",
  app_quit: "system_change",
  desktop_open_app: "local_open",
  window_close_all: "system_change",
  window_hide_all: "system_change",
  window_minimize_all: "system_change",
  window_auto_arrange: "system_change",
  window_minimize_unrelated: "system_change",
  window_close: "system_change",
  window_minimize: "system_change",
  window_maximize: "system_change",
  window_move_resize: "system_change",
  desktop_show: "system_change",
  system_close_app: "system_change",
  system_sleep: "system_change",
  system_lock_screen: "system_change",
  system_set_volume: "system_change",
  system_mute_volume: "system_change",
  system_set_brightness: "system_change",
  system_set_dark_mode: "system_change",
  system_open_settings: "local_open",
  desktop_clipboard_write: "local_write",
  system_speak: "local_open",
  system_notification: "system_change",
  screenshot_capture: "system_change",
  keyboard_shortcut: "system_change",
  browser_open_url: "local_open",
  browser_search_open: "local_open",
  browser_isolated_open_url: "local_open",
  browser_isolated_window_focus: "local_open",
  browser_isolated_window_move_resize: "system_change",
  browser_fill_form: "browser_submit",
  browser_click: "browser_submit",
  advanced_shell_command: "shell",
};

export const queueManagedToolDefinitions = allToolDefinitions.filter((definition) => definition.name in toolGroupByName);
