import { z } from "zod";
import { config } from "../config";
import { toolGroups, type ToolName } from "./metadata";

const limitSchema = z.number().int().min(1).max(10).optional().default(5);
const folderNameSchema = z.string().min(1).refine(
  (value) => {
    const trimmed = value.trim();
    return Boolean(trimmed) && trimmed !== "." && trimmed !== ".." && !trimmed.includes("/") && !trimmed.includes("\\");
  },
  { message: "folderName must be a valid folder name without slashes." },
);

export const toolSchemas: Record<ToolName, z.ZodTypeAny> = {
  system_status: z.object({}),
  confirmation_list: z.object({}),
  confirmation_decide: z.object({ confirmationId: z.string().min(1).optional(), approved: z.boolean() }),
  tool_result_read: z.object({
    handle: z.string().min(1),
    offset: z.number().int().min(0).optional().default(0),
    maxChars: z.number().int().min(200).max(6000).optional().default(2000),
  }),
  tool_catalog_list: z.object({ group: z.enum(toolGroups).optional() }),
  tool_group_set: z.object({ group: z.enum(toolGroups), enabled: z.boolean() }),
  task_create: z.object({
    toolName: z.string().min(1),
    arguments: z.record(z.string(), z.unknown()).optional().default({}),
    priority: z.enum(["low", "normal", "high"]).optional().default("normal"),
    runAfterMs: z.number().int().min(0).max(600000).optional().default(0),
  }),
  task_status: z.object({ taskId: z.string().min(1) }),
  task_list: z.object({
    status: z.enum(["queued", "running", "completed", "failed", "cancelled", "needs_confirmation"]).optional(),
    limit: z.number().int().min(1).max(30).optional().default(10),
  }),
  task_cancel: z.object({ taskId: z.string().min(1) }),
  task_route: z.object({
    userRequest: z.string().min(1),
    preference: z.enum(["auto", "native", "search", "codex"]).optional().default("auto"),
    cwd: z.string().min(1).optional(),
    activeApp: z.string().min(1).optional(),
    selectedText: z.string().optional(),
  }),
  intent_route: z.object({
    intent: z.object({
      originalText: z.string().min(1),
      intent: z.string().min(1),
      complexity: z.enum(["simple", "complex", "ambiguous"]),
      domain: z.enum([
        "desktop",
        "apps",
        "windows",
        "system",
        "media",
        "social",
        "research",
        "calendar",
        "reminder",
        "notes",
        "weather",
        "travel",
        "browser",
        "files",
        "documents",
        "email",
        "coding",
        "research",
        "phone",
        "memory",
        "unknown",
      ]),
      action: z.string().optional(),
      entities: z.record(z.string(), z.unknown()).optional().default({}),
      toolName: z.string().optional(),
      toolArguments: z.record(z.string(), z.unknown()).optional().default({}),
      candidateTools: z.array(z.string()).optional().default([]),
      missingInfo: z.array(z.string()).optional().default([]),
      confidence: z.number().min(0).max(1),
      routePreference: z.enum(["auto", "direct", "codex", "clarify"]).optional().default("auto"),
    }),
    cwd: z.string().min(1).optional(),
    activeApp: z.string().min(1).optional(),
    selectedText: z.string().optional(),
  }),
  memory_lookup: z.object({
    query: z.string().min(1),
    types: z.array(z.enum(["path_alias", "preference", "task_template"])).optional(),
    limit: z.number().int().min(1).max(10).optional().default(5),
  }),
  memory_save: z.object({
    type: z.enum(["path_alias", "preference", "task_template"]),
    key: z.string().min(1),
    value: z.string().optional(),
    summary: z.string().optional(),
    content: z.string().optional(),
    aliases: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
  memory_forget: z.object({ idOrKey: z.string().min(1) }),
  memory_status: z.object({}),
  codex_task_run: z.object({
    prompt: z.string().min(1),
    cwd: z.string().min(1).optional(),
    model: z.string().min(1).optional(),
    sandbox: z.enum(["read_only", "workspace_write"]).optional().default("read_only"),
    timeoutMs: z.number().int().min(10000).max(1800000).optional().default(config.codexTurnTimeoutMs),
    memoryIds: z.array(z.string()).optional().default([]),
  }),
  yolo_mode_set: z.object({ enabled: z.boolean() }),
  file_list: z.object({ path: z.string().min(1), includeHidden: z.boolean().optional().default(false) }),
  file_search: z.object({ root: z.string().min(1), query: z.string(), maxDepth: z.number().int().min(1).max(8).optional().default(4), limit: z.number().int().min(1).max(50).optional().default(20) }),
  file_read: z.object({ path: z.string().min(1), maxChars: z.number().int().min(100).max(10000).optional().default(3000) }),
  file_open: z.object({ path: z.string().min(1), appName: z.string().min(1).optional() }),
  file_create_folder: z.object({ parentPath: z.string().min(1), folderName: folderNameSchema }),
  file_rename: z.object({ path: z.string().min(1), newName: z.string().min(1) }),
  file_move: z.object({ from: z.string().min(1), to: z.string().min(1) }),
  file_copy: z.object({ from: z.string().min(1), to: z.string().min(1) }),
  file_trash: z.object({ path: z.string().min(1) }),
  document_extract: z.object({ path: z.string().min(1), maxChars: z.number().int().min(500).max(10000).optional().default(3000) }),
  document_folder_digest: z.object({ root: z.string().min(1), query: z.string().optional(), limit: z.number().int().min(1).max(5).optional().default(3), charsPerFile: z.number().int().min(300).max(2000).optional().default(1000) }),
  document_prepare_edit: z.object({ path: z.string().min(1), newContent: z.string() }),
  email_search: z.object({ query: z.string().min(1), limit: limitSchema }),
  email_read: z.object({ emailId: z.string().min(1) }),
  email_draft: z.object({ to: z.string().min(1), subject: z.string().min(1), body: z.string().min(1) }),
  email_send: z.object({ draftId: z.string().min(1) }),
  mac_mail_draft_create: z.object({ to: z.string().email(), subject: z.string().min(1), body: z.string().min(1) }),
  weather_lookup: z.object({ location: z.string().min(1), date: z.string().min(1).optional() }),
  calendar_search: z.object({ from: z.string().min(1), to: z.string().min(1), query: z.string().optional(), limit: z.number().int().min(1).max(20).optional().default(10) }),
  calendar_create: z.object({
    title: z.string().min(1),
    start: z.string().min(1),
    end: z.string().min(1),
    attendees: z.array(z.string()).optional().default([]),
    location: z.string().optional(),
    notes: z.string().optional(),
  }),
  mac_calendar_create: z.object({
    title: z.string().min(1),
    start: z.string().min(1),
    end: z.string().min(1),
    calendarName: z.string().min(1).optional(),
    location: z.string().optional(),
    notes: z.string().optional(),
    attendees: z.array(z.string()).optional().default([]),
  }),
  mac_reminder_create: z.object({
    title: z.string().min(1),
    dueAt: z.string().min(1).optional(),
    listName: z.string().min(1).optional(),
    notes: z.string().optional(),
  }),
  mac_note_create: z.object({
    title: z.string().min(1),
    body: z.string().min(1),
    folderName: z.string().min(1).optional(),
  }),
  copy_search: z.object({ query: z.string().min(1), limit: limitSchema }),
  copy_save_draft: z.object({ title: z.string().min(1), body: z.string().min(1), project: z.string().optional() }),
  copy_publish: z.object({ draftId: z.string().min(1) }),
  music_open: z.object({}),
  music_play_song: z.object({ query: z.string().min(1), artist: z.string().optional(), mode: z.enum(["play", "search"]).optional().default("play") }),
  music_playback_state: z.object({}),
  music_spotify_search: z.object({ query: z.string().min(1), artist: z.string().optional(), limit: z.number().int().min(1).max(10).optional().default(5) }),
  music_spotify_play: z.object({ query: z.string().min(1), artist: z.string().optional(), deviceId: z.string().min(1).optional() }),
  music_spotify_playback_state: z.object({}),
  music_netease_open: z.object({ query: z.string().min(1).optional(), url: z.string().url().optional() }),
  music_qq_open: z.object({ query: z.string().min(1).optional(), target: z.enum(["app", "web"]).optional().default("web") }),
  media_key_control: z.object({ action: z.enum(["play_pause", "next", "previous", "volume_up", "volume_down"]), appName: z.string().min(1).optional() }),
  video_play: z.object({ service: z.enum(["youtube", "apple_tv", "bilibili"]), query: z.string().min(1), mode: z.enum(["play", "search"]).optional().default("play") }),
  video_playback_control: z.object({ action: z.enum(["play", "pause", "toggle", "state"]) }),
  apple_tv_playback_state: z.object({}),
  social_x_search: z.object({ query: z.string().min(1), limit: z.number().int().min(10).max(100).optional().default(10) }),
  social_x_post: z.object({ text: z.string().min(1).max(280), replyToTweetId: z.string().min(1).optional() }),
  social_open: z.object({
    service: z.enum(["x", "xiaohongshu"]),
    kind: z.enum(["home", "search", "profile", "note", "share"]).optional().default("search"),
    target: z.string().optional(),
    isolated: z.boolean().optional().default(true),
  }),
  news_search: z.object({
    query: z.string().min(1),
    provider: z.enum(["gdelt", "newsapi"]).optional().default("gdelt"),
    limit: z.number().int().min(1).max(25).optional().default(8),
  }),
  sec_filing_search: z.object({
    company: z.string().min(1),
    forms: z.array(z.string().min(1)).optional().default([]),
    limit: z.number().int().min(1).max(30).optional().default(10),
  }),
  macro_series_lookup: z.object({
    seriesId: z.string().min(1),
    startYear: z.string().min(4).max(4).optional(),
    endYear: z.string().min(4).max(4).optional(),
  }),
  market_quote_lookup: z.object({ symbol: z.string().min(1) }),
  shortcut_list: z.object({ limit: z.number().int().min(1).max(50).optional().default(20) }),
  shortcut_run: z.object({
    name: z.string().min(1),
    input: z.string().optional(),
    timeoutMs: z.number().int().min(1000).max(180000).optional().default(60000),
  }),
  contacts_search: z.object({ query: z.string().min(1), limit: z.number().int().min(1).max(10).optional().default(5) }),
  phone_call: z.object({
    phoneNumber: z.string().min(1),
    contactName: z.string().min(1).optional(),
    mode: z.enum(["phone", "facetime_audio", "facetime_video"]).optional().default("phone"),
  }),
  app_open: z.object({ appName: z.string().min(1) }),
  app_focus: z.object({ appName: z.string().min(1) }),
  app_quit: z.object({ appName: z.string().min(1) }),
  window_list: z.object({}),
  window_close_all: z.object({}),
  window_hide_all: z.object({
    preserveFrontmost: z.boolean().optional().default(false),
    preserveFinder: z.boolean().optional().default(true),
  }),
  window_minimize_all: z.object({}),
  window_auto_arrange: z.object({ appNames: z.array(z.string().min(1)).optional().default([]) }),
  window_minimize_unrelated: z.object({
    keepAppNames: z.array(z.string().min(1)).optional().default([]),
    keepTitleKeywords: z.array(z.string().min(1)).optional().default([]),
    preserveFrontmost: z.boolean().optional().default(true),
  }),
  window_close: z.object({ appName: z.string().min(1) }),
  window_minimize: z.object({ appName: z.string().min(1) }),
  window_maximize: z.object({ appName: z.string().min(1) }),
  window_move_resize: z.object({
    appName: z.string().min(1),
    x: z.number().int(),
    y: z.number().int(),
    width: z.number().int().min(120),
    height: z.number().int().min(120),
  }),
  desktop_show: z.object({}),
  desktop_open_app: z.object({ appName: z.string().min(1) }),
  system_close_app: z.object({ appName: z.string().min(1) }),
  system_sleep: z.object({}),
  system_lock_screen: z.object({}),
  system_set_volume: z.object({ level: z.number().int().min(0).max(100) }),
  system_get_volume: z.object({}),
  system_mute_volume: z.object({ muted: z.boolean() }),
  system_set_brightness: z.object({ level: z.number().int().min(0).max(100) }),
  system_set_dark_mode: z.object({ enabled: z.boolean() }),
  system_open_settings: z.object({ pane: z.string().optional() }),
  desktop_clipboard_write: z.object({ text: z.string().min(1) }),
  desktop_clipboard_read: z.object({}),
  system_speak: z.object({ text: z.string().min(1), voice: z.string().min(1).optional() }),
  system_notification: z.object({ title: z.string().min(1), message: z.string().min(1), dialog: z.boolean().optional().default(false) }),
  screenshot_capture: z.object({ mode: z.enum(["clipboard", "desktop", "selection"]) }),
  keyboard_shortcut: z.object({
    action: z.enum(["copy", "paste", "select_all", "undo", "enter", "escape", "tab", "new_window", "new_tab", "refresh", "browser_back", "browser_forward", "toggle_fullscreen"]),
  }),
  browser_open_url: z.object({ url: z.string().url() }),
  browser_search_open: z.object({
    query: z.string().min(1),
    engine: z.enum(["google", "bing", "duckduckgo"]).optional().default("google"),
    isolated: z.boolean().optional().default(true),
  }),
  browser_isolated_open_url: z.object({ url: z.string().url() }),
  browser_isolated_window_focus: z.object({}),
  browser_isolated_window_move_resize: z.object({
    x: z.number().int(),
    y: z.number().int(),
    width: z.number().int().min(120),
    height: z.number().int().min(120),
  }),
  browser_read_page: z.object({ maxChars: z.number().int().min(200).max(10000).optional().default(3000) }),
  browser_read_video_state: z.object({}),
  browser_fill_form: z.object({ fields: z.array(z.object({ selector: z.string().min(1), value: z.string() })).min(1).max(30) }),
  browser_click: z.object({ selector: z.string().min(1), purpose: z.string().min(1) }),
  advanced_shell_command: z.object({ command: z.string().min(1), reason: z.string().min(1), timeoutMs: z.number().int().min(1000).max(20000).optional().default(10000) }),
  app_permission_search: z.object({ query: z.string(), limit: z.number().int().min(1).max(20).optional().default(8) }),
  app_permission_set: z.object({ appName: z.string().min(1), authorized: z.boolean() }),
  capability_set: z.object({ capability: z.enum(["fileManagement", "browserAutomation", "textOperations", "systemOperations"]), enabled: z.boolean() }),
};
