import type { WorkflowPack } from "../../shared/workflows";

export const builtInWorkflowPacks: WorkflowPack[] = [
  {
    id: "focus_writing",
    title: "Focus Writing",
    description: "Prepare a quiet writing surface with relevant files, a Notes scratchpad, and unrelated windows minimized after review.",
    triggers: ["focus writing", "start writing mode", "进入写作专注", "帮我开始写作"],
    parameters: [
      { name: "root", description: "Folder to search for drafts.", defaultValue: "~/Documents" },
      { name: "query", description: "Draft filename or topic filter.", defaultValue: ".md" },
      { name: "noteTitle", description: "Scratch note title.", defaultValue: "Focus Writing Session" },
      { name: "noteBody", description: "Scratch note body.", defaultValue: "Goal:\n\nOutline:\n\nNext action:" },
    ],
    requiredCapabilities: ["fileManagement", "textOperations", "systemOperations"],
    risks: ["read", "local_write", "system_change"],
    steps: [
      {
        id: "find-drafts",
        title: "Find recent writing files",
        toolName: "file_search",
        arguments: { root: "{{root}}", query: "{{query}}", maxDepth: 3, limit: 8 },
        rollbackNote: "Read-only search; no rollback needed.",
      },
      {
        id: "create-scratch-note",
        title: "Create writing scratch note",
        toolName: "mac_note_create",
        arguments: { title: "{{noteTitle}}", body: "{{noteBody}}" },
        rollbackNote: "Remove the created note from Notes if it is not useful.",
      },
      {
        id: "minimize-distractions",
        title: "Minimize unrelated windows",
        toolName: "window_minimize_unrelated",
        arguments: {
          keepAppNames: ["Notes", "TextEdit", "Pages", "Microsoft Word", "Visual Studio Code"],
          keepTitleKeywords: ["draft", "writing", "note", "outline"],
          preserveFrontmost: true,
        },
        rollbackNote: "Restore minimized windows from the Dock.",
      },
    ],
    rollbackNotes: [
      "Read-only file search has no side effect.",
      "Created Notes items can be deleted from Notes.",
      "Minimized windows can be restored from the Dock.",
    ],
  },
  {
    id: "meeting_prep",
    title: "Meeting Prep",
    description: "Collect meeting context, open Calendar, and draft a preparation note before any event creation is confirmed.",
    triggers: ["meeting prep", "prepare my meeting", "准备会议", "开会前帮我准备"],
    parameters: [
      { name: "meetingTitle", description: "Meeting title or topic.", defaultValue: "Meeting Prep" },
      { name: "from", description: "Calendar search lower bound.", defaultValue: "2026-06-15T00:00:00" },
      { name: "to", description: "Calendar search upper bound.", defaultValue: "2026-06-22T23:59:59" },
      { name: "start", description: "Optional prep block start time.", defaultValue: "2026-06-15T09:00:00" },
      { name: "end", description: "Optional prep block end time.", defaultValue: "2026-06-15T09:30:00" },
    ],
    requiredCapabilities: ["textOperations", "systemOperations"],
    risks: ["read", "local_open", "local_write"],
    steps: [
      {
        id: "search-calendar",
        title: "Search calendar context",
        toolName: "calendar_search",
        arguments: { from: "{{from}}", to: "{{to}}", query: "{{meetingTitle}}", limit: 5 },
        rollbackNote: "Read-only search; no rollback needed.",
      },
      {
        id: "open-calendar",
        title: "Open Calendar",
        toolName: "app_open",
        arguments: { appName: "Calendar" },
        rollbackNote: "Close Calendar if it is not needed.",
      },
      {
        id: "create-prep-note",
        title: "Create meeting prep note",
        toolName: "mac_note_create",
        arguments: { title: "{{meetingTitle}} Prep", body: "Agenda:\n\nQuestions:\n\nDecisions needed:" },
        rollbackNote: "Delete the created prep note from Notes if it is not useful.",
      },
      {
        id: "optional-prep-block",
        title: "Create optional prep block",
        toolName: "mac_calendar_create",
        arguments: {
          title: "{{meetingTitle}} prep",
          start: "{{start}}",
          end: "{{end}}",
          notes: "Created by Her Meeting Prep workflow after confirmation.",
          attendees: [],
        },
        optional: true,
        rollbackNote: "Delete the created prep calendar event.",
      },
    ],
    rollbackNotes: [
      "Calendar search is read-only.",
      "Opened apps can be closed normally.",
      "Created Notes and Calendar items can be removed from their native apps.",
    ],
  },
  {
    id: "research_desk",
    title: "Research Desk",
    description: "Open an isolated research browser, scan local documents, and create a source-tracking note.",
    triggers: ["research desk", "start research", "进入研究模式", "帮我查资料"],
    parameters: [
      { name: "query", description: "Research query.", defaultValue: "Her local agent runtime" },
      { name: "root", description: "Folder containing local research docs.", defaultValue: "~/Documents" },
    ],
    requiredCapabilities: ["browserAutomation", "fileManagement", "textOperations"],
    risks: ["read", "local_open", "local_write"],
    steps: [
      {
        id: "open-research-search",
        title: "Open isolated web research",
        toolName: "browser_search_open",
        arguments: { query: "{{query}}", engine: "google", isolated: true },
        rollbackNote: "Close the isolated browser window.",
      },
      {
        id: "digest-local-docs",
        title: "Digest local research documents",
        toolName: "document_folder_digest",
        arguments: { root: "{{root}}", query: "{{query}}", limit: 3, charsPerFile: 800 },
        rollbackNote: "Read-only digest; no rollback needed.",
      },
      {
        id: "create-research-note",
        title: "Create research desk note",
        toolName: "mac_note_create",
        arguments: { title: "Research Desk: {{query}}", body: "Sources:\n\nClaims:\n\nOpen questions:" },
        rollbackNote: "Delete the created research note from Notes.",
      },
    ],
    rollbackNotes: [
      "Close the isolated browser window when finished.",
      "Local document digest is read-only.",
      "Created Notes items can be deleted from Notes.",
    ],
  },
  {
    id: "coding_session",
    title: "Coding Session",
    description: "Inspect a repo, open the coding surface, and start a reviewable Codex coding-agent run after confirmation.",
    triggers: ["coding session", "start coding", "进入编程模式", "帮我开始写代码"],
    parameters: [
      { name: "repoPath", description: "Repository path.", defaultValue: "." },
      { name: "prompt", description: "Coding-agent task.", defaultValue: "Inspect the repository and propose the next safe implementation step." },
    ],
    requiredCapabilities: ["fileManagement", "systemOperations"],
    risks: ["read", "local_open", "coding_agent"],
    steps: [
      {
        id: "find-project-files",
        title: "Find project files",
        toolName: "file_search",
        arguments: { root: "{{repoPath}}", query: "package.json", maxDepth: 3, limit: 10 },
        rollbackNote: "Read-only search; no rollback needed.",
      },
      {
        id: "open-editor",
        title: "Open code editor",
        toolName: "app_open",
        arguments: { appName: "Visual Studio Code" },
        optional: true,
        rollbackNote: "Close the editor if it is not needed.",
      },
      {
        id: "start-codex-review",
        title: "Start Codex coding-agent review",
        toolName: "coding_agent_start",
        arguments: { repoPath: "{{repoPath}}", prompt: "{{prompt}}", mode: "plan", timeoutMs: 300000 },
        rollbackNote: "Cancel the coding-agent task before it completes, or discard its isolated worktree output.",
      },
    ],
    rollbackNotes: [
      "File search is read-only.",
      "Opened apps can be closed normally.",
      "Codex runs are isolated and require review before any apply step.",
    ],
  },
  {
    id: "file_cleanup",
    title: "File Cleanup",
    description: "Review candidate files first, then move one explicit target to Trash only after confirmation.",
    triggers: ["file cleanup", "clean files", "清理文件", "帮我整理文件"],
    parameters: [
      { name: "root", description: "Folder to search.", defaultValue: "~/Downloads" },
      { name: "query", description: "Candidate filename filter.", defaultValue: ".tmp" },
      { name: "targetPath", description: "Exact file or folder to move to Trash.", required: false },
    ],
    requiredCapabilities: ["fileManagement"],
    risks: ["read", "local_write"],
    steps: [
      {
        id: "find-cleanup-candidates",
        title: "Find cleanup candidates",
        toolName: "file_search",
        arguments: { root: "{{root}}", query: "{{query}}", maxDepth: 4, limit: 20 },
        rollbackNote: "Read-only search; no rollback needed.",
      },
      {
        id: "trash-explicit-target",
        title: "Move explicit target to Trash",
        toolName: "file_trash",
        arguments: { path: "{{targetPath}}" },
        rollbackNote: "Restore the item from Trash if the confirmed target was wrong.",
      },
    ],
    rollbackNotes: [
      "Candidate search is read-only.",
      "Only an explicit target path can be moved, and only after confirmation.",
      "Trash moves are reversible through macOS Trash.",
    ],
  },
];

export const workflowPackById = new Map(builtInWorkflowPacks.map((pack) => [pack.id, pack]));
